# Generated by Django 5.2.13 on 2026-09-10 12:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Calendario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "versao",
                    models.CharField(max_length=60, unique=True, verbose_name="Versão"),
                ),
                (
                    "titulo",
                    models.CharField(blank=True, max_length=200, verbose_name="Título"),
                ),
                (
                    "periodo",
                    models.CharField(blank=True, max_length=40, verbose_name="Período"),
                ),
                ("data_inicio", models.DateField(verbose_name="Início do semestre")),
                (
                    "total_semanas",
                    models.PositiveIntegerField(
                        default=18, verbose_name="Nº de semanas"
                    ),
                ),
                (
                    "semanas_primeira_parte",
                    models.PositiveIntegerField(
                        default=9, verbose_name="Semanas na 1ª parte"
                    ),
                ),
                ("etapa", models.PositiveIntegerField(default=1, verbose_name="Etapa")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("rascunho", "Rascunho"),
                            ("etapa", "Etapa"),
                            ("final", "Final"),
                        ],
                        default="etapa",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "final",
                    models.BooleanField(default=False, verbose_name="Versão final"),
                ),
                (
                    "atual",
                    models.BooleanField(default=False, verbose_name="Versão atual"),
                ),
                (
                    "observacoes",
                    models.TextField(blank=True, verbose_name="Observações"),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Calendário",
                "verbose_name_plural": "Calendários",
                "ordering": ["-data_inicio", "-etapa", "versao"],
            },
        ),
        migrations.CreateModel(
            name="Feriado",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data", models.DateField(verbose_name="Data")),
                (
                    "descricao",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Descrição"
                    ),
                ),
                (
                    "origem",
                    models.CharField(
                        choices=[
                            ("nacional", "Nacional"),
                            ("institucional", "Institucional"),
                            ("manual", "Manual"),
                        ],
                        default="manual",
                        max_length=20,
                        verbose_name="Origem",
                    ),
                ),
                (
                    "calendario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feriados",
                        to="calendario.calendario",
                    ),
                ),
            ],
            options={
                "verbose_name": "Feriado",
                "verbose_name_plural": "Feriados",
                "ordering": ["data"],
                "unique_together": {("calendario", "data")},
            },
        ),
    ]
