# Generated by Django 5.2.13 on 2026-09-10 14:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("calendario", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="calendario",
            name="curso",
            field=models.CharField(blank=True, max_length=200, verbose_name="Curso"),
        ),
        migrations.AddField(
            model_name="calendario",
            name="data_fim",
            field=models.DateField(
                blank=True, null=True, verbose_name="Término do período letivo"
            ),
        ),
        migrations.AddField(
            model_name="calendario",
            name="dias_letivos_por_mes",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Lista de {'mes': 'SET/2026', 'letivos': 13} para conferência.",
                verbose_name="Dias letivos declarados por mês",
            ),
        ),
        migrations.AddField(
            model_name="calendario",
            name="dias_letivos_previstos",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Dias letivos previstos"
            ),
        ),
        migrations.AddField(
            model_name="calendario",
            name="instituicao",
            field=models.CharField(
                blank=True,
                default="Instituto Federal de Educação, Ciência e Tecnologia do Piauí — IFPI — Campus Barras",
                max_length=200,
                verbose_name="Instituição",
            ),
        ),
        migrations.AddField(
            model_name="calendario",
            name="modalidade",
            field=models.CharField(
                blank=True,
                choices=[
                    ("integrado", "Integrado"),
                    ("integrado_proeja", "Integrado PROEJA"),
                    ("subsequente", "Subsequente"),
                    ("proeja", "PROEJA"),
                    ("superior", "Superior"),
                    ("outro", "Outro"),
                ],
                default="integrado_proeja",
                max_length=30,
                verbose_name="Modalidade",
            ),
        ),
        migrations.AddField(
            model_name="calendario",
            name="semestre",
            field=models.CharField(blank=True, max_length=20, verbose_name="Semestre"),
        ),
        migrations.AddField(
            model_name="feriado",
            name="tipo",
            field=models.CharField(
                choices=[
                    ("feriado", "Feriado"),
                    ("ponto_facultativo", "Ponto facultativo"),
                ],
                default="feriado",
                max_length=20,
                verbose_name="Tipo",
            ),
        ),
        migrations.CreateModel(
            name="Evento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=200, verbose_name="Título")),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("letivo", "Dia letivo"),
                            ("sabado_letivo", "Sábado letivo"),
                            ("sabado_reposicao", "Sábado de reposição"),
                            ("feriado", "Feriado"),
                            ("ponto_facultativo", "Ponto facultativo"),
                            ("jornada_pedagogica", "Jornada pedagógica"),
                            ("recesso", "Recesso escolar"),
                            ("ferias_coletivas", "Férias coletivas"),
                            ("avaliacao", "Avaliação"),
                            ("avaliacao_final", "Avaliação final"),
                            ("recuperacao", "Recuperação paralela"),
                            ("conselho_classe", "Conselho de classe"),
                            ("matricula", "Matrícula"),
                            ("administrativo", "Administrativo"),
                            ("evento", "Evento institucional"),
                        ],
                        default="evento",
                        max_length=30,
                        verbose_name="Tipo",
                    ),
                ),
                ("data_inicio", models.DateField(verbose_name="Data inicial")),
                (
                    "data_fim",
                    models.DateField(blank=True, null=True, verbose_name="Data final"),
                ),
                (
                    "dia_semana_referencia",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        choices=[
                            (0, "Segunda-feira"),
                            (1, "Terça-feira"),
                            (2, "Quarta-feira"),
                            (3, "Quinta-feira"),
                            (4, "Sexta-feira"),
                        ],
                        help_text="Usado em sábados letivos/de reposição (qual dia da semana é reposto).",
                        null=True,
                        verbose_name="Dia da semana referenciado",
                    ),
                ),
                ("descricao", models.TextField(blank=True, verbose_name="Descrição")),
                (
                    "destaque",
                    models.BooleanField(default=False, verbose_name="Destaque"),
                ),
                (
                    "calendario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="eventos",
                        to="calendario.calendario",
                    ),
                ),
            ],
            options={
                "verbose_name": "Evento",
                "verbose_name_plural": "Eventos",
                "ordering": ["data_inicio", "titulo"],
            },
        ),
    ]
