# Generated by Django 5.2.13 on 2026-09-10 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("calendario", "0002_calendario_curso_calendario_data_fim_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="calendario",
            name="atual",
        ),
        migrations.RemoveField(
            model_name="calendario",
            name="final",
        ),
        migrations.RemoveField(
            model_name="calendario",
            name="status",
        ),
    ]
