# Generated by Django 5.2.13 on 2026-09-11 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("calendario", "0003_remove_calendario_atual_remove_calendario_final_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="feriado",
            name="origem",
            field=models.CharField(
                choices=[
                    ("nacional", "Nacional"),
                    ("estadual", "Estadual"),
                    ("municipal", "Municipal"),
                    ("institucional", "Institucional"),
                    ("manual", "Manual"),
                ],
                default="manual",
                max_length=20,
                verbose_name="Origem",
            ),
        ),
    ]
