# Generated by Django 5.2.13 on 2026-09-11 10:45
# Ajustada à mão: além do ``AlterField``, mapeia as modalidades antigas para as
# três atuais (arts. 38, 39 e 40 do regulamento).

from django.db import migrations, models

#: modalidade antiga → modalidade atual
MAPA_MODALIDADES = {
    "integrado": "integrado_medio",
    "integrado_proeja": "integrado_medio",
    "proeja": "integrado_medio",
    "medio": "integrado_medio",
    "subsequente": "concomitante_subsequente",
    "concomitante": "concomitante_subsequente",
    "superior": "graduacao",
    "outro": "graduacao",
}


def mapear_modalidades(apps, schema_editor):
    """Converte os valores antigos de ``modalidade`` para os três atuais."""
    Calendario = apps.get_model("calendario", "Calendario")
    for cal in Calendario.objects.all():
        novo = MAPA_MODALIDADES.get((cal.modalidade or "").strip())
        if novo and novo != cal.modalidade:
            cal.modalidade = novo
            cal.save(update_fields=["modalidade"])


def desfazer_modalidades(apps, schema_editor):
    """Sem volta: os valores antigos não têm correspondência 1:1 (no-op documentado)."""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("calendario", "0004_feriado_origem_esferas"),
    ]

    operations = [
        migrations.RunPython(mapear_modalidades, desfazer_modalidades),
        migrations.AlterField(
            model_name="calendario",
            name="modalidade",
            field=models.CharField(
                blank=True,
                choices=[
                    ("integrado_medio", "Cursos técnicos integrados ao nível médio"),
                    (
                        "concomitante_subsequente",
                        "Cursos técnicos concomitantes/subsequentes",
                    ),
                    ("graduacao", "Graduação"),
                ],
                default="integrado_medio",
                max_length=30,
                verbose_name="Modalidade",
            ),
        ),
    ]
