"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.13.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-8c1f%calendario-academico-ifpi-barras-#2026"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["*"]


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "calendario",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "config.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "calendario.context_processors.site",
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "pt-br"

TIME_ZONE = "America/Fortaleza"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "/static/"
STATICFILES_DIRS = [BASE_DIR / "static"]
STATIC_ROOT = BASE_DIR / "staticfiles"

MEDIA_URL = "media/"
MEDIA_ROOT = BASE_DIR / "media"


def _normalize_base(raw):
    raw = (raw or "/").strip()
    if not raw.startswith("/"):
        raw = "/" + raw
    if not raw.endswith("/"):
        raw += "/"
    return raw


# Site base URL (subpath do GitHub Pages), calculado dinamicamente no CI.
# Ex.: "/gerenciador_calendario/" para project pages, ou "/" para user/org pages.
SITE_BASE_URL = _normalize_base(os.environ.get("SITE_BASE_URL", "/"))
SITE_URL = os.environ.get("SITE_URL", "").rstrip("/")


def _flag(nome, padrao=True):
    """Lê uma variável de ambiente booleana (``0``/``false``/``no`` desligam)."""
    valor = os.environ.get(nome)
    if valor is None or not valor.strip():
        return padrao
    return valor.strip().lower() not in ("0", "false", "no", "off")


# ---- LLM (preenchimento assistido dos eventos) -----------------------------
# As chaves ficam **somente** em variáveis de ambiente; nada é versionado e os
# valores nunca chegam ao navegador nem ao site estático (o editor não é publicado).
#
#   export DEEPSEEK_API_KEY="sk-..."
#   export LLM_PROVIDER="deepseek"      # deepseek | openai | gemini | anthropic
#
LLM_ENABLED = _flag("LLM_ENABLED", True)
LLM_DEFAULT_PROVIDER = os.environ.get("LLM_PROVIDER", "deepseek").strip().lower()
LLM_TIMEOUT = int(os.environ.get("LLM_TIMEOUT", "120"))
LLM_MAX_TOKENS = int(os.environ.get("LLM_MAX_TOKENS", "8000"))
LLM_TEMPERATURE = float(os.environ.get("LLM_TEMPERATURE", "0.2"))

# Localização padrão da unidade (usada como valor inicial no modal do editor).
LLM_CIDADE_PADRAO = os.environ.get("LLM_CIDADE_PADRAO", "Barras")
LLM_ESTADO_PADRAO = os.environ.get("LLM_ESTADO_PADRAO", "PI")
LLM_PAIS_PADRAO = os.environ.get("LLM_PAIS_PADRAO", "Brasil")

#: Provedores suportados. ``dialeto`` define o formato do corpo da requisição:
#: ``openai`` (ChatGPT/OpenAI e DeepSeek), ``gemini`` (Google) e ``anthropic``.
LLM_PROVIDERS = {
    "deepseek": {
        "label": "DeepSeek",
        "dialeto": "openai",
        "url": os.environ.get("DEEPSEEK_API_URL", "https://api.deepseek.com/chat/completions"),
        "model": os.environ.get("DEEPSEEK_MODEL", "deepseek-chat"),
        "api_key": os.environ.get("DEEPSEEK_API_KEY", ""),
    },
    "openai": {
        "label": "ChatGPT (OpenAI)",
        "dialeto": "openai",
        "url": os.environ.get("OPENAI_API_URL", "https://api.openai.com/v1/chat/completions"),
        "model": os.environ.get("OPENAI_MODEL", "gpt-4o-mini"),
        "api_key": os.environ.get("OPENAI_API_KEY", ""),
    },
    "gemini": {
        "label": "Gemini (Google)",
        "dialeto": "gemini",
        "url": os.environ.get(
            "GEMINI_API_URL",
            "https://generativelanguage.googleapis.com/v1beta/models/{model}:generateContent",
        ),
        "model": os.environ.get("GEMINI_MODEL", "gemini-2.0-flash"),
        "api_key": os.environ.get("GEMINI_API_KEY", ""),
    },
    "anthropic": {
        "label": "Claude (Anthropic)",
        "dialeto": "anthropic",
        "url": os.environ.get("ANTHROPIC_API_URL", "https://api.anthropic.com/v1/messages"),
        "model": os.environ.get("ANTHROPIC_MODEL", "claude-sonnet-4-5"),
        "api_key": os.environ.get("ANTHROPIC_API_KEY", ""),
    },
}

#: Apelidos aceitos nas configurações/entrada (ex.: ``chatgpt`` → ``openai``).
LLM_PROVIDER_ALIASES = {
    "chatgpt": "openai",
    "gpt": "openai",
    "openai": "openai",
    "claude": "anthropic",
    "claudecode": "anthropic",
    "anthropic": "anthropic",
    "google": "gemini",
    "gemini": "gemini",
    "deepseek": "deepseek",
}

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# Parâmetros padrão do calendário acadêmico (podem ser sobrescritos no editor).
CALENDARIO_SEMANAS_PADRAO = int(os.environ.get("CALENDARIO_SEMANAS_PADRAO", "18"))
CALENDARIO_SEMANAS_1A_PARTE = int(os.environ.get("CALENDARIO_SEMANAS_1A_PARTE", "9"))
